# -*- coding: utf-8 -*-
"""AI Blogger Using Gemini API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WuPp_CGKOEACiRqkiXdb_jcTkuBqD64
"""

#Install the Google AI Python SDK
!pip install google-generativeai

import os
import google.generativeai as genai

from google.colab import userdata
genai.configure(api_key=userdata.get('API_KEY'))

# Create the model
generation_config = {
  "temperature": 2,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-pro",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
  system_instruction="Act as an experienced blogger who knows about all the topics in this world. You will be receiving a blog post topic as an input and you have to write a crisp and humanly toned blog post. Do not make up fake stuff and try to be very factual and quote stats related to that topic if possible to make the end result accurate. Keep the word count at around 150 words. Do not cross this word limit.",
)

chat_session = model.start_chat(
  history=[
    {
      "role": "user",
      "parts": [
        "Java",
      ],
    },
    {
      "role": "model",
      "parts": [
        "## Java: A Legacy Still Going Strong \n\nJava, the brainchild of Sun Microsystems (now Oracle), has been a cornerstone of the programming world for decades. Known for its \"write once, run anywhere\" philosophy, Java's platform independence made it a favorite for everything from web applications to embedded systems. \n\nWhile newer languages have emerged, Java's popularity endures. The  [2022 Stack Overflow Developer Survey](https://survey.stackoverflow.co/2022/#section-most-popular-technologies-programming-scripting-and-markup-languages)  ranks Java as the 5th most commonly used language, a testament to its robust ecosystem and vast community support. \n\nWhy is it still relevant? Simply put, Java offers a powerful blend of stability, scalability, and versatility. With millions of developers worldwide and countless resources available, Java remains a wise choice for both seasoned professionals and aspiring programmers. \n",
      ],
    },
    {
      "role": "user",
      "parts": [
        "Maruti Suzuki Swift",
      ],
    },
    {
      "role": "model",
      "parts": [
        "## The Maruti Suzuki Swift: India's Darling Hatchback\n\nThe Maruti Suzuki Swift needs little introduction in India. This zippy hatchback, launched in 2005, quickly became a national favorite known for its stylish design, peppy performance, and impressive fuel efficiency.  \n\nIt's no surprise the Swift consistently ranks among the top-selling cars in India. In 2022 alone, Maruti Suzuki sold over [170,000 units](https://www.autocarindia.com/car-news/top-10-bestselling-cars-of-2022-maruti-suzuki-dominates-426052), proving its enduring appeal to Indian car buyers. \n\nWhat's the secret sauce? The Swift blends practicality and affordability without compromising on style and driving dynamics. With its competitive pricing and wide service network, it continues to be a top choice for first-time car buyers and seasoned drivers alike. \n",
      ],
    },
  ]
)

# Send a new message and receive the response
response = chat_session.send_message("Google")
print(response.text)